spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sblog?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Shanghai
mybatis:
  configuration:
    map-underscore-to-camel-case: true #??????
  mapper-locations: classpath:mapper/*.xml